const express = require('express');
const { BattleStream } = require('pokemon-showdown');

const app = express();
app.use(express.json());

// In-memory storage for active battles
// In a real production environment, this could be clustered or managed via Redis pub/sub
const activeBattles = new Map();

app.post('/api/battle/create', (req, res) => {
    const { matchId, formatId, p1, p2 } = req.body;

    if (!matchId || !formatId || !p1 || !p2) {
        return res.status(400).json({ error: 'Missing required parameters' });
    }

    const stream = new BattleStream();
    
    // We will collect the logs generated by this action
    let currentLogs = [];
    
    // Set up consumer
    const consumeStream = async () => {
        for await (const chunk of stream) {
            currentLogs.push(chunk);
        }
    };
    consumeStream();

    activeBattles.set(matchId, {
        stream,
        logs: currentLogs
    });

    // Initialize battle
    stream.write(`>start {"formatid":"${formatId}"}`);
    stream.write(`>player p1 {"name":"${p1.name}"}`);
    stream.write(`>player p2 {"name":"${p2.name}"}`);

    // Wait a brief moment for the initial logs to generate
    setTimeout(() => {
        const logs = [...currentLogs];
        currentLogs.length = 0; // Clear read logs
        res.json({ matchId, logs });
    }, 100);
});

app.post('/api/battle/action', (req, res) => {
    const { matchId, player, action } = req.body;
    
    const battle = activeBattles.get(matchId);
    if (!battle) {
        return res.status(404).json({ error: 'Battle not found' });
    }

    // Write action to stream. Example action: "move 1", "switch 2"
    battle.stream.write(`>${player} ${action}`);

    // Wait a brief moment for simulation to process and generate logs
    setTimeout(() => {
        const logs = [...battle.logs];
        battle.logs.length = 0; // Clear read logs
        res.json({ matchId, logs });
    }, 100);
});

const PORT = process.env.PORT || 8084;
app.listen(PORT, () => {
    console.log(`Node.js Sim RPC Service running on port ${PORT}`);
});
